name: "Build & Release"
on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      -dev
      -test

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    -name: Checkout Repository
     uses: actions/checkout@v4

    -name: Set Up Java
      uses: action/setup-jave@v4.0.0
      with:
        distribution: 'oracle'
        java-version: '21'   

    -name: Set Up Flutter  
      uses: subosito/flutter-action@v2.12.0
      with:
        flutter-version: '3.16.3'
        channel: 'stable'

    -name: Install Dependencies
      run: flutter pub get

    -name: Test flutter app
      run: flutter test

    -name: Build APK
      run: flutter build apk --release

    -name: Build appBundle
      run: flutter build appbundle

    -name: Upload Artifacts
      uses: actions/upload-artifact@v4.0.0
      with: 
        name: Releases
        path: |
          build/app/outputs/flutter-apk/app-release.apl
          build/app/outputs/bundle/release/app-release.aab
          build/ios_build.tar.gz

    -name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release,apk,build/app/outputs/bundle/release/app-release/app.release.aab,build/ios_build.tar.gz"
        tag: v1.0.${{github.run_number}}
        token:${{ github.token }}

